### ISSUE TITLE
Setup the whole project

### ISSUE THREAD

**Issue by TeddyGandon** [TeddyGandon/thefirstspine-boardgamearena#1]
Setup the project with:
- [x] add composer file
- [x] add composer depedency: https://github.com/fguillot/JsonRPC
- [x] create a batch script deployment
