### ISSUE TITLE
Create the game instance

### ISSUE THREAD

**Issue by TeddyGandon** [TeddyGandon/thefirstspine-boardgamearena#2]
Create the game instance
- [ ] alter database to have to game ID in the database
- [ ] create the JsonRPC client
- [ ] create the game and save it in the database
