### ISSUE TITLE
Create mysql schemas

### ISSUE THREAD

**Issue by TeddyGandon** [TeddyGandon/thefirstspine-boardgamearena#3]
- [x] Schema for players
- [x] Schema for characters and cards
- [ ] Schema for game logs (with the complete history of the turns)
