### ISSUE TITLE
Create software design

### ISSUE THREAD

**Issue by TeddyGandon** [TeddyGandon/thefirstspine-boardgamearena#4]
Objective: create a design pattern approaching to the MVC for the project (main app should be a singleton). The models are here to bind data to database. The drivers describes ways to communicate with other services (e.g. APIs, databases, etc.)

The base classes must be in a composer depedency.

- [x] Create the app singleton
- [ ] Create the drivers base & structure
- [ ] Create the  models base & structure

**EDIT:**

It's better to use some facades and adapters to enhance the app:
- [ ] Create a Facade system with abstracts accessors
- [ ] The database driver should be registered in the Facade

The main game app will act a a frontal controller, which call some other controllers.

**Comment by TeddyGandon** [comment]
Beware:
In the doc "no exotic development"

**Comment by TeddyGandon** [comment]
It's better to use some facades and adapters to enhance the app:
- [ ] Create a Facade system with abstracts accessors
- [ ] The database driver should be registered in the Facade

The main game app will act a a frontal controller, which call some other controllers.

**Comment by TeddyGandon** [comment]
http://en.doc.boardgamearena.com/Main_game_logic:_yourgamename.game.php

> The main game logic should be the only point from where you should access to the game database

This issue must be closed.
