### ISSUE TITLE
Create the models

### ISSUE THREAD

**Issue by TeddyGandon** [TeddyGandon/thefirstspine-boardgamearena#5]
The models must bind data to database, using the DB driver.

- [ ] Create the model Gamelog
- [ ] Create the model Global
- [ ] Create the model Player
- [ ] Create the model Stats
- [ ] Create the model Character
- [ ] Create the model Card

**Comment by TeddyGandon** [comment]
http://en.doc.boardgamearena.com/Main_game_logic:_yourgamename.game.php

> The main game logic should be the only point from where you should access to the game database

This issue must be closed.
